exclude:      ['README.md', 'Gemfile.lock', 'Gemfile']
title:        'Juraj Blahunka'
tagline:      'Juraj Blahunka | Java enthusiast'
description:  'A Java enthusiast'
url:          http://juraj.blahunka.eu
version:      1.1.1
author:
  name:       'Juraj Blahunka'
  email:      'blahunka.juraj@gmail.com'
markdown:     rdiscount
permalink:    pretty
highlighter:  pygments
pygments:     true
paginate:     5
