exclude:      ['README.md', 'Gemfile.lock', 'Gemfile']
title:        'Juraj Blahunka'
tagline:      'Juraj Blahunka | Swift enthusiast'
description:  'A -Java- Swift enthusiast'
url:          http://juraj.blahunka.eu
version:      1.1.1
author:
  name:       'Juraj Blahunka'
  email:      'blahunka.juraj@gmail.com'
markdown:     kramdown
permalink:    pretty
highlighter:  rouge
paginate:     5
